# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: cloudcare-hospital-frontend
#   labels:
#     app: cloudcare-hospital
#     tier: frontend
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: cloudcare-hospital
#       tier: frontend
#   template:
#     metadata:
#       labels:
#         app: cloudcare-hospital
#         tier: frontend
#     spec:
#       containers:
#       - name: frontend
#         image: cloudcare-hospital-frontend:latest
#         imagePullPolicy: IfNotPresent
#         ports:
#         - containerPort: 80
#           name: http
#           protocol: TCP
#         resources:
#           requests:
#             memory: "128Mi"
#             cpu: "100m"
#           limits:
#             memory: "256Mi"
#             cpu: "200m"
#         env:
#         - name: NODE_ENV
#           value: "production"
#       restartPolicy: Always





apiVersion: apps/v1
kind: Deployment

metadata:
  name: cloudcare-hospital-frontend
  labels:
    app: cloudcare-hospital
    tier: frontend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: cloudcare-hospital
      tier: frontend

  template:
    metadata:
      labels:
        app: cloudcare-hospital
        tier: frontend

    spec:
      containers:
        - name: frontend

          image: vaibhavvelumuri/careconnect_hospital-portel-frontend:v1

          imagePullPolicy: Always

          ports:
            - containerPort: 80
              protocol: TCP
              name: http

          env:
            - name: NODE_ENV
              value: "production"

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: cloudcare-hospital-backend
  labels:
    app: cloudcare-hospital
    tier: backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: cloudcare-hospital
      tier: backend

  template:
    metadata:
      labels:
        app: cloudcare-hospital
        tier: backend

    spec:
      containers:
        - name: backend

          image: vaibhavvelumuri/careconnect_hospital-portel-backend:v1

          imagePullPolicy: Always

          ports:
            - containerPort: 5000
              protocol: TCP
              name: http

          env:
            - name: PORT
              value: "5000"

            # - name: DB_HOST
            #   value: "mysql"

            # - name: DB_USER
            #   value: "root"

            # - name: DB_PASSWORD
            #   value: "rootpassword"

            # - name: DB_NAME
            #   value: "hospital_management"

            - name: NODE_ENV
              value: "production"