# apiVersion: v1
# kind: Service
# metadata:
#   name: cloudcare-hospital-frontend-service
#   labels:
#     app: cloudcare-hospital
#     tier: frontend
# spec:
#   type: NodePort
#   selector:
#     app: cloudcare-hospital
#     tier: frontend
#   ports:
#   - port: 80
#     targetPort: 80
#     nodePort: 30080
#     protocol: TCP
#     name: http


apiVersion: v1
kind: Service

metadata:
  name: cloudcare-hospital-frontend-service
  labels:
    app: cloudcare-hospital
    tier: frontend

spec:
  type: NodePort

  selector:
    app: cloudcare-hospital
    tier: frontend

  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
      name: http

---
apiVersion: v1
kind: Service

metadata:
  name: cloudcare-hospital-backend-service
  labels:
    app: cloudcare-hospital
    tier: backend

spec:
  type: ClusterIP

  selector:
    app: cloudcare-hospital
    tier: backend

  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http